name: Deploy react-app

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: self-hosted  
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Node.js version
        run: |
          nvm install
          nvm use

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build
          
      - name: Deploy to Nginx
        run: |
          sudo cp -r ./build/* /var/www/html

      - name: Restart Nginx
        run: |
          sudo systemctl restart nginx
